FROM node:23-alpine

ARG REDIS_URL
ARG DATABASE_URL

RUN apk add --no-cache python3 make g++

WORKDIR /app

RUN npm install -g pnpm


COPY package.json pnpm-lock.yaml ./
COPY turbo.json ./
COPY pnpm-workspace.yaml ./

COPY apps/worker/ apps/worker/
COPY packages/ packages/

RUN pnpm install
RUN DATABASE_URL=${DATABASE_URL} pnpm --filter db exec prisma generate

RUN pnpm run build-worker

EXPOSE 3012

CMD ["pnpm", "run", "start-worker"]