name: Build and Deploy to Docker Hub & VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build worker and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile.worker
        push: true
        tags: asistiwari96/playfi-worker:latest
        build-args: |
          REDIS_URL=${{ secrets.REDIS_URL }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}


    - name: Build web and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile.web
        push: true
        tags: asistiwari96/playfi-web:latest
        build-args: |
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
    
    - name: Build ws and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile.ws
        push: true
        tags: asistiwari96/playfi-ws:latest
        build-args: |
          REDIS_URL=${{ secrets.REDIS_URL }}
          NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
        command_timeout: "40m"    
        script: |
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker stop playfi-ws || true
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker rm playfi-ws || true
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker stop playfi-web || true
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker rm playfi-web || true
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker stop playfi-worker || true
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker rm playfi-worker || true

          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker pull asistiwari96/playfi-ws:latest
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker pull asistiwari96/playfi-web:latest
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker pull asistiwari96/playfi-worker:latest

          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker run -d --name playfi-ws \
            --network playfi \
            -e REDIS_URL=${{ secrets.REDIS_URL }} \
            -e NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
            -p 3014:3014 --restart always \
            asistiwari96/playfi-ws:latest

          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker run -d --name playfi-worker \
            --network playfi \
            -e REDIS_URL=${{ secrets.REDIS_URL }} \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -p 3012:3012 --restart always \
            asistiwari96/playfi-worker:latest


          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker run -d --name playfi-web \
            --network playfi \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            -e GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            -e NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
            -e NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} \
            -p 3013:3013 --restart always \
            asistiwari96/playfi-web:latest

          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker image prune -f